Repository adobe/aem-cif-guides-venia, pull requests merged in 2020-10, with the labels that each got.

#66 CIF-1630 - Configurable header tag for teaser and carousel components
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/catalog-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/landing-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/page-content/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/root-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/xf-web-variation/policies/.content.xml
Labels: enhancement, verified

#67 releng - Prepare Release with CIF Core Components 1.4.0
  pom.xml
Labels: releng

#69 releng - Prepare Release with CIF Core Components 1.4.0 (React Components)
  ui.frontend/package-lock.json
  ui.frontend/package.json
Labels: releng

#70 2020.10.02 Release
  ui.frontend/package-lock.json
  ui.frontend/package.json
Labels: releng

#76 Enable dataLayer on custom component
  core/src/main/java/com/venia/core/models/commerce/MyProductTeaserImpl.java
  core/src/test/java/com/venia/core/models/commerce/MyProductTeaserImplTest.java
  it.tests/src/main/java/com/venia/it/tests/CategoryPageIT.java
  it.tests/src/main/java/com/venia/it/tests/ProductPageIT.java
  it.tests/src/main/java/com/venia/it/tests/SearchPageIT.java
  it.tests/src/main/java/com/venia/it/utils/Utils.java
  it.tests/src/main/resources/datalayer/grouped-product.json
  it.tests/src/main/resources/datalayer/placeholder-category-items.json
  it.tests/src/main/resources/datalayer/placeholder-product.json
  it.tests/src/main/resources/datalayer/sample-category-gallery.json
  it.tests/src/main/resources/datalayer/sample-category-items.json
  it.tests/src/main/resources/datalayer/sample-searchresult-gallery.json
  it.tests/src/main/resources/datalayer/sample-searchresult-items.json
  it.tests/src/main/resources/datalayer/simple-product.json
  pom.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/productteaser/productteaser.html
  ui.content/src/main/content/jcr_root/conf/venia/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/.content.xml
Labels: enhancement, verified

#77 CIF-1673 - add commerce teaser styles & corresponding policies
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/catalog-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/landing-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/page-content/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/root-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/xf-web-variation/policies/.content.xml
  ui.frontend/src/main/styles/_teaser.scss
  ui.frontend/src/main/styles/teaser/_banner-dark.scss
  ui.frontend/src/main/styles/teaser/_banner-light.scss
  ui.frontend/src/main/styles/teaser/_feature-left.scss
  ui.frontend/src/main/styles/teaser/_feature-right.scss
Labels: enhancement, verified

#78 CIF-1668 - Add webdriver.io UI tests
  .circleci/ci/it-tests.js
  .circleci/config.yml
  .gitignore
  pom.xml
  ui.tests/.dockerignore
  ui.tests/Dockerfile
  ui.tests/README.md
  ui.tests/assembly-ui-test-docker-context.xml
  ui.tests/docker-compose-wdio-chrome.yaml
  ui.tests/docker-compose-wdio-firefox.yaml
  ui.tests/pom.xml
  ui.tests/test-module/.eslintrc.js
  ui.tests/test-module/README.md
  ui.tests/test-module/assets/image.png
  ui.tests/test-module/lib/commons.js
  ui.tests/test-module/lib/config.js
  ui.tests/test-module/lib/wdio.commands.js
  ui.tests/test-module/package.json
  ui.tests/test-module/specs/venia/react.js
  ui.tests/test-module/wdio.conf.cloud.js
  ui.tests/test-module/wdio.conf.commons.js
  ui.tests/test-module/wdio.conf.local.js
  ui.tests/wait-for-grid.sh
Labels: enhancement

#72 CIF-1608 - Category Carousel Component
  ui.apps/src/main/content/jcr_root/apps/venia/clientlibs/clientlib-cif/.content.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/categorycarousel/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/catalog-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/landing-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/page-content/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/root-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/xf-web-variation/policies/.content.xml
  ui.frontend/src/main/styles/commerce/_carousel.scss
  ui.frontend/src/main/styles/commerce/_categorycarousel.scss
Labels: enhancement

#74 CIF-1629 - Enrich PLP / PDP automatically with metadata
  .circleci/ci/it-tests.js
  .circleci/config.yml
  it.tests/src/main/java/com/venia/it/tests/CategoryPageIT.java
  it.tests/src/main/java/com/venia/it/tests/ProductPageIT.java
Labels: testing

#83 CIF-1697: Fix maven package auto install
  all/pom.xml
  pom.xml
  ui.config/pom.xml
Labels: bug
