Repository adobe/aem-cif-guides-venia, pull requests merged in 2020-07, with the labels that each got.

#18 CIF-1488 - add missing cq:conf for XF
  ui.content/src/main/content/jcr_root/content/experience-fragments/venia/.content.xml
Labels: bug, verified

#10 CIF-1444: Add 'miniaccount' component to the header of page templates in venia storefront
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/miniaccount/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/catalog-page/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/landing-page/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/page-content/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/root-page/structure/.content.xml
  ui.frontend/README.md
  ui.frontend/clientlib.config.js
  ui.frontend/package.json
  ui.frontend/pom.xml
  ui.frontend/src/main/components/App/App.js
  ui.frontend/src/main/components/App/config.js
  ui.frontend/src/main/components/App/i18n.js
  ui.frontend/src/main/site/styles/header.scss
  ui.frontend/src/main/styles/commerce/_navigation.scss
  ui.frontend/src/main/webpack/components/commerce/_navigation.scss
  ui.frontend/src/main/webpack/site/styles/header.scss
  ui.frontend/webpack.common.js
  ui.frontend/webpack.dev.js
Labels: To Verify, enhancement

#21 CIF-1505 -
  README.md
  ui.apps/src/main/content/jcr_root/apps/venia/config.publish/org.apache.sling.jcr.resource.internal.JcrResourceResolverFactoryImpl.xml
Labels: documentation

#22 CIF-1525 - use correct super type for button component
  ui.apps/src/main/content/jcr_root/apps/venia/components/button/.content.xml
Labels: bug, verified

#20 CIF-1489 - Default product binding is missing in the Venia repo
  .gitignore
  ui.content/pom.xml
  ui.content/src/main/content/filter-templates/filter-classic.xml
  ui.content/src/main/content/filter-templates/filter-cloud.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/cloudconfigs/commerce/.content-classic.xml
  ui.content/src/main/content/jcr_root/var/commerce/products/venia-default/.content.xml
Labels: bug, verified
