Repository adobe/aem-cif-guides-venia, pull requests merged in 2020-11, with the labels that each got.

#80 CIF-1654 - CIF React Core Components should support GraphQL GET requests
  .gitignore
  pom.xml
  ui.frontend/src/main/components/App/App.js
Labels: enhancement, verified

#85 CIF-1678 - Commerce Teaser should align HTL files with WCM core component
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/teaser/.content.xml
  ui.frontend/src/main/styles/_teaser.scss
Labels: enhancement

#89 CIF-1752 - Add default cache configuration for Venia
  ui.config/src/main/content/jcr_root/apps/venia/osgiconfig/config/com.adobe.cq.commerce.graphql.client.impl.GraphqlClientImpl~default.cfg.json
Labels: bug

#88 CIF-1501 - XF based page footer with authoring support
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/catalogpage/customfooterlibs.html
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/catalogpage/customheaderlibs.html
  ui.apps/src/main/content/jcr_root/apps/venia/components/footer/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/template-types/page/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/catalog-page/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/landing-page/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/page-content/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/root-page/structure/.content.xml
  ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/footer/master/.content.xml
  ui.tests/test-module/package.json
Labels: enhancement
