Repository adobe/aem-cif-guides-venia, pull requests merged in 2020-09, with the labels that each got.

#47 CIF-1587 - Add reverse proxy and dispatcher to documentation
  README.md
Labels: documentation

#40 CIF-1546 - Pass the DOM nodes in which the components render as props
  ui.frontend/src/main/components/App/App.js
  ui.frontend/src/main/components/App/config.js
Labels: enhancement, verified

#39 CIF-1473: Support Bundle Products: option selection
  ui.frontend/src/main/components/App/App.js
  ui.frontend/src/main/components/App/config.js
  ui.frontend/src/main/styles/commerce/_product.scss
Labels: do not merge, enhancement

#50 CIF-1500 - Setup IT project for Venia Demo
  .circleci/ci/it-tests.js
  it.tests/src/main/java/com/venia/it/tests/CategoryPageIT.java
  it.tests/src/main/java/com/venia/it/tests/LandingPageIT.java
  it.tests/src/main/java/com/venia/it/tests/ProductPageIT.java
  it.tests/src/main/java/com/venia/it/tests/SearchPageIT.java
Labels: testing

#44 CIF-1551 - [React Components] Refactor the NavigationContext
  ui.frontend/src/main/components/App/config.js
Labels: To Verify, enhancement

#52 CIF-1592 - Update filter mode for templates to fix upgrades
  ui.content/src/main/content/filter-templates/filter-classic.xml
  ui.content/src/main/content/filter-templates/filter-cloud.xml
Labels: bug

#55 CIF-1625 Setup dev branch with snapshot dependencies
  .circleci/config.yml
  .github/codecov.yml
  README.md
Labels: releng

#54 CIF-1612 - adjust Venia for CIF Core Components package changes
  all/pom.xml
  pom.xml
  ui.apps/pom.xml
  ui.content/pom.xml
Labels: To Verify, enhancement

#56 CIF-1640 - Productcollection clientlib is not included in Venia demo
  ui.apps/src/main/content/jcr_root/apps/venia/clientlibs/clientlib-cif/.content.xml
Labels: bug, verified

#57 Update README.md
  README.md
Labels: documentation, releng

#60 CIF-1084 - Implement the password reset page
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/resetpassword/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/en/reset-password/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/reset-password/.content.xml
  ui.frontend/src/main/components/App/App.js
  ui.frontend/src/main/components/App/config.js
Labels: enhancement, verified

#61 CIF-1609 - Lazy Loading for PLP
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/initial/.content.xml
  ui.frontend/src/main/styles/commerce/_productlist.scss
Labels: enhancement, verified
