Repository adobe/aem-cif-guides-venia, pull requests merged in 2020-08, with the labels that each got.

#23 CIF-1398 - [My Account] Address book management
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/addressbook/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/en/my-account/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/en/my-account/address-book/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/my-account/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/my-account/address-book/.content.xml
  ui.frontend/package.json
  ui.frontend/src/main/components/App/App.js
  ui.frontend/src/main/components/App/config.js
Labels: verified

#24 CIF-1547 - [React Components] Fix CSS reusability
  ui.frontend/src/main/site/main.scss
  ui.frontend/src/main/styles/commerce/_minicart.scss
  ui.frontend/src/main/webpack/components/_accordion.scss
  ui.frontend/src/main/webpack/components/_breadcrumb.scss
  ui.frontend/src/main/webpack/components/_button.scss
  ui.frontend/src/main/webpack/components/_carousel.scss
  ui.frontend/src/main/webpack/components/_container.scss
  ui.frontend/src/main/webpack/components/_contentfragment.scss
  ui.frontend/src/main/webpack/components/_contentfragmentlist.scss
  ui.frontend/src/main/webpack/components/_download.scss
  ui.frontend/src/main/webpack/components/_experiencefragment.scss
  ui.frontend/src/main/webpack/components/_form-button.scss
  ui.frontend/src/main/webpack/components/_form-options.scss
  ui.frontend/src/main/webpack/components/_form-text.scss
  ui.frontend/src/main/webpack/components/_form.scss
  ui.frontend/src/main/webpack/components/_helloworld.js
  ui.frontend/src/main/webpack/components/_heroimage-variables.scss
  ui.frontend/src/main/webpack/components/_heroimage.scss
  ui.frontend/src/main/webpack/components/_image.scss
  ui.frontend/src/main/webpack/components/_languagenavigation.scss
  ui.frontend/src/main/webpack/components/_list.scss
  ui.frontend/src/main/webpack/components/_navigation.scss
  ui.frontend/src/main/webpack/components/_search.scss
  ui.frontend/src/main/webpack/components/_tabs.scss
  ui.frontend/src/main/webpack/components/_teaser.scss
  ui.frontend/src/main/webpack/components/_text.scss
  ui.frontend/src/main/webpack/components/_title.scss
  ui.frontend/src/main/webpack/components/commerce/_featuredcategorylist.scss
  ui.frontend/src/main/webpack/components/commerce/_loadingindicator.scss
  ui.frontend/src/main/webpack/components/commerce/_minicart-flow.scss
  ui.frontend/src/main/webpack/components/commerce/_minicart-icons.scss
  ui.frontend/src/main/webpack/components/commerce/_minicart.scss
  ui.frontend/src/main/webpack/components/commerce/_navigation.scss
  ui.frontend/src/main/webpack/components/commerce/_product.scss
  ui.frontend/src/main/webpack/components/commerce/_productcarousel.scss
  ui.frontend/src/main/webpack/components/commerce/_productlist.scss
  ui.frontend/src/main/webpack/components/commerce/_productteaser.scss
  ui.frontend/src/main/webpack/components/commerce/_searchresults.scss
  ui.frontend/src/main/webpack/resources/fonts/.gitkeep
  ui.frontend/src/main/webpack/resources/images/.gitkeep
  ui.frontend/src/main/webpack/resources/images/close.svg
  ui.frontend/src/main/webpack/resources/images/heart.svg
  ui.frontend/src/main/webpack/resources/images/kebab.svg
  ui.frontend/src/main/webpack/resources/images/lock.svg
  ui.frontend/src/main/webpack/resources/images/logo.svg
  ui.frontend/src/main/webpack/resources/images/pencil.svg
  ui.frontend/src/main/webpack/resources/images/trash.svg
  ui.frontend/src/main/webpack/site/_base.scss
  ui.frontend/src/main/webpack/site/_variables.scss
  ui.frontend/src/main/webpack/site/main.scss
  ui.frontend/src/main/webpack/site/main.ts
  ui.frontend/src/main/webpack/site/styles/common.scss
  ui.frontend/src/main/webpack/site/styles/container_main.scss
  ui.frontend/src/main/webpack/site/styles/experiencefragment_footer.scss
  ui.frontend/src/main/webpack/site/styles/experiencefragment_header.scss
  ui.frontend/src/main/webpack/site/styles/footer.scss
  ui.frontend/src/main/webpack/site/styles/header.scss
  ui.frontend/src/main/webpack/static/index.html
  ui.frontend/webpack.common.js
Labels: verified

#25 CIF-1519 - Fix /etc/map config to resolve PDPs correctly
  ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/category-page-reverse/.content.xml
  ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/category-page/.content.xml
  ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/product-page-reverse/.content.xml
  ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/product-page/.content.xml
Labels: bug, verified

#28 CIF-1490 - Add maven classifiers to Venia content packages
  .circleci/ci/deploy-venia.js
  all/pom.xml
  pom.xml
  ui.apps.structure/pom.xml
  ui.apps/pom.xml
  ui.content/pom.xml
Labels: verified

#29 CIF-1564 - Venia CSS for search filters is missing
  ui.frontend/src/main/resources/images/logo.svg
  ui.frontend/src/main/styles/commerce/_loadingindicator.scss
  ui.frontend/src/main/styles/commerce/_productlist.scss
  ui.frontend/src/main/styles/commerce/_searchresults.scss
Labels: bug, verified

#31 CIF-1569 - Product duplicates in cart
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/productteaser/productteaser.html
Labels: bug, verified

#32 CIF-1571 - Venia demo home page doesn't contain the text 'Venia Demo Store' any more
  ui.content/src/main/content/jcr_root/content/venia/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/en/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/en/my-account/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/en/my-account/address-book/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/en/products/category-page/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/en/products/product-page/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/en/search/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/my-account/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/my-account/address-book/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/products/category-page/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/products/product-page/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/search/.content.xml
Labels: To Verify, bug

#37 CIF-1574 - Release Venia store demo on Github
  README.md
  pom.xml
Labels: releng

#30 CIF-1538 - Expose CIF page paths in xfpage property dialog
  ui.apps/src/main/content/jcr_root/apps/venia/components/xfpage/_cq_dialog/.content.xml
Labels: verified

#33 CIF-1546 - Pass the DOM nodes in which the components render as props
  ui.frontend/src/main/components/App/App.js
  ui.frontend/src/main/components/App/config.js
Labels: verified

#36 CIF-1572 - The installation profile of Venia Demo fails on the main b…
  all/pom.xml
  core/pom.xml
  pom.xml
  ui.apps/pom.xml
  ui.content/pom.xml
Labels: bug, verified

#43 CIF-1540 - CIF breadcrumb component
  pom.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/breadcrumb/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/catalog-page/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/landing-page/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/page-content/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/structure/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/en/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/.content.xml
  ui.frontend/src/main/styles/_breadcrumb.scss
Labels: To Verify, enhancement

#46 CIF-1499 - Setup IT infrastructure for Venia Demo
  .circleci/ci/it-tests.js
  .circleci/config.yml
Labels: testing

#41 CIF-1548 - Add customization instructions for CSS template
  ui.frontend/README.md
Labels: enhancement

#48 CIF-1500 - Setup IT project for Venia Demo
  .circleci/ci/it-tests.js
  .circleci/config.yml
  it.tests/src/main/java/com/venia/it/tests/CategoryPageIT.java
  it.tests/src/main/java/com/venia/it/tests/CommerceTestBase.java
  it.tests/src/main/java/com/venia/it/tests/CreatePageIT.java
  it.tests/src/main/java/com/venia/it/tests/GetPageIT.java
  it.tests/src/main/java/com/venia/it/tests/GraphqlOSGiConfig.java
  it.tests/src/main/java/com/venia/it/tests/LandingPageIT.java
  it.tests/src/main/java/com/venia/it/tests/ProductPageIT.java
  it.tests/src/main/java/com/venia/it/tests/SearchPageIT.java
Labels: testing

#45 CIF-1590 - Add Muli font to Venia CSS
  ui.frontend/src/main/site/main.scss
Labels: bug
