Repository adobe/aem-cif-guides-venia, pull requests merged in 2021-11, with the labels that each got.

#219 CIF-2368 - Increase contrast ratio for product teaser title and price
  ui.frontend/src/main/styles/commerce/_productteaser.scss
Labels: bug, verified

#221 CIF-2512: set tag name format to match the previous tag names
  pom.xml
Labels: bug, verified

#220 CIF-2195 - Add additional recommendation types
  pom.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/catalog-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/landing-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/page-content/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/root-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/xf-web-variation/policies/.content.xml
  ui.frontend/package-lock.json
  ui.frontend/package.json
Labels: enhancement, verified

#222 CIF-2458: deploy venia cloud artefacts to maven central
  .circleci/ci/deploy-venia.js
  .circleci/config.yml
  pom.xml
  ui.tests/pom.xml
Labels: releng

#212 CIF-1656: Enhance account information
  .circleci/ci/it-tests.js
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/orderhistory/.content.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/resetpassword/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/en/my-account/order-history/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/en/reset-password/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/my-account/order-history/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/reset-password/.content.xml
  ui.frontend/i18n/en.json
  ui.frontend/src/main/components/AccountInformationPage/__tests__/__snapshots__/accountInformationPage.spec.js.snap
  ui.frontend/src/main/components/AccountInformationPage/__tests__/accountInformationPage.spec.js
  ui.frontend/src/main/components/AccountInformationPage/accountInformationPage.js
  ui.frontend/src/main/components/AccountInformationPage/index.js
  ui.frontend/src/main/components/AccountMenu/__tests__/__snapshots__/accountMenu.spec.js.snap
  ui.frontend/src/main/components/AccountMenu/__tests__/__snapshots__/accountMenuItems.spec.js.snap
  ui.frontend/src/main/components/AccountMenu/__tests__/accountMenu.spec.js
  ui.frontend/src/main/components/AccountMenu/__tests__/accountMenuItems.spec.js
  ui.frontend/src/main/components/AccountMenu/accountMenu.js
  ui.frontend/src/main/components/AccountMenu/accountMenuItems.js
  ui.frontend/src/main/components/AccountMenu/index.js
  ui.frontend/src/main/components/AccountMenu/useAccountMenuItems.js
  ui.frontend/src/main/components/AddressBookPage/__tests__/__snapshots__/addressBookPage.spec.js.snap
  ui.frontend/src/main/components/AddressBookPage/__tests__/addressBookPage.spec.js
  ui.frontend/src/main/components/AddressBookPage/addressBookPage.js
  ui.frontend/src/main/components/AddressBookPage/index.js
  ui.frontend/src/main/components/App/App.js
  ui.frontend/src/main/components/App/config.js
  ui.frontend/src/main/components/CartPage/PriceSummary/priceSummary.js
  ui.frontend/src/main/components/CartPage/ProductListing/product.js
  ui.frontend/src/main/components/CartPage/ProductListing/productListing.js
  ui.frontend/src/main/components/CartPage/cartPage.js
  ui.frontend/src/main/components/Header/accountTrigger.css
  ui.frontend/src/main/components/Header/accountTrigger.js
  ui.frontend/src/main/components/Header/cartTrigger.js
  ui.frontend/src/main/components/MiniCart/miniCart.js
  ui.frontend/src/main/components/OrderHistoryPage/__tests__/__snapshots__/orderHistoryPage.spec.js.snap
  ui.frontend/src/main/components/OrderHistoryPage/__tests__/orderHistoryPage.spec.js
  ui.frontend/src/main/components/OrderHistoryPage/index.js
  ui.frontend/src/main/components/OrderHistoryPage/orderHistoryPage.js
  ui.frontend/src/main/site/styles/header.scss
  ui.frontend/src/main/talons/AddressBookPage/useAddressBookPage.js
  ui.frontend/src/main/talons/OrderHistoryPage/useOrderHistoryPage.js
  ui.frontend/webpack.common.js
  ui.tests/README.md
  ui.tests/test-module/lib/config.js
  ui.tests/test-module/specs/venia/react.js
Labels: enhancement

#228 CIF-2514: Add support for gift card product
  ui.frontend/src/main/components/App/App.js
  ui.frontend/src/main/components/App/config.js
  ui.frontend/src/main/site/styles/common.scss
  ui.frontend/src/main/styles/commerce/_product.scss
Labels: enhancement
