Repository adobe/aem-cif-guides-venia, pull requests merged in 2021-08, with the labels that each got.

#173 CIF-2251: adds sitemap configurations
  dispatcher-cloud/src/conf.d/rewrites/rewrite.rules
  dispatcher-cloud/src/conf.dispatcher.d/filters/filters.any
  ui.config/src/main/content/jcr_root/apps/venia/osgiconfig/config.publish/org.apache.sling.sitemap.impl.SitemapScheduler~default.cfg.json
  ui.content/src/main/content/jcr_root/content/venia/us/en/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/my-account/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/my-account/account-details/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/my-account/address-book/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/products/category-page/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/products/product-page/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/reset-password/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/search/.content.xml
Labels: enhancement

#176 CIF-1502 - XF based page header with authoring support
  it.tests/src/main/resources/datalayer/grouped-product.json
  it.tests/src/main/resources/datalayer/placeholder-product.json
  it.tests/src/main/resources/datalayer/simple-product.json
  pom.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/accountdetails/.content.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/addressbook/.content.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/logo/.content.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/logo/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/logo/logo.html
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/miniaccount/.content.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/minicart/.content.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/navigation/.content.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/resetpassword/.content.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/searchbar/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/template-types/page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/template-types/page/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/catalog-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/catalog-page/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/structure/_jcr_content/root/header/logo.svg
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/landing-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/landing-page/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/landing-page/structure/_jcr_content/root/header/logo.svg
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/page-content/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/page-content/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/page-content/structure/_jcr_content/root/header/logo.svg
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/structure/_jcr_content/root/header/logo.svg
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/root-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/root-page/structure/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/root-page/structure/_jcr_content/root/header/logo.svg
  ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/header/master/.content.xml
  ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/header/master/_jcr_content/root/logo/logo.svg
  ui.frontend/src/main/components/App/config.js
  ui.frontend/src/main/site/styles/header.scss
  ui.frontend/src/main/styles/_navigation.scss
  ui.frontend/src/main/styles/commerce/_navigation.scss
Labels: enhancement

#177 CIF-2177 - Expose configured product identifiers for components
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/productteaser/productteaser.html
Labels: enhancement

#179 CIF-2272 - Cannot close category filter accordion once it is open
  ui.tests/test-module/specs/venia/productcollection.js
Labels: bug

#178 CIF-2291 - Cleanups in searchbar component
  ui.apps/src/main/content/jcr_root/apps/venia/clientlibs/clientlib-cif/.content.xml
  ui.frontend/src/main/site/styles/header.scss
  ui.tests/test-module/specs/venia/searchbar.js
Labels: enhancement, verified
