Repository adobe/aem-cif-guides-venia, pull requests merged in 2021-06, with the labels that each got.

#135 CIF-2065 - Set affinity cookie for all requests in WDIO tests
  .circleci/config.yml
  ui.tests/test-module/lib/commons.js
Labels: testing

#140 CIF-2135 - Rename component to "Commerce Experience Fragment"
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/experiencefragment/.content.xml
  ui.tests/test-module/specs/venia/component-dialogs.js
Labels: bug, verified

#138 CIF-1748 - Content Fragment Commerce component
  pom.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/contentfragment/.content.xml
  ui.tests/test-module/.eslintrc.js
  ui.tests/test-module/.prettierignore
  ui.tests/test-module/.prettierrc
  ui.tests/test-module/lib/config.js
  ui.tests/test-module/lib/wdio.commands.js
  ui.tests/test-module/package.json
  ui.tests/test-module/specs/venia/catalog-page-dialogs.js
  ui.tests/test-module/specs/venia/component-dialogs.js
  ui.tests/test-module/specs/venia/content-fragment-component-dialog.js
  ui.tests/test-module/specs/venia/react.js
  ui.tests/test-module/specs/venia/xf-page-dialogs.js
  ui.tests/test-module/wdio.conf.cloud.js
  ui.tests/test-module/wdio.conf.commons.js
  ui.tests/test-module/wdio.conf.local.js
Labels: enhancement, verified

#143 CIF-2140 - add sample styles for commerce CF
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/catalog-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/policies/.content.xml
  ui.frontend/src/main/styles/_contentfragment.scss
Labels: enhancement, verified

#139 CIF-2107 - Add Magento Storefront Events SDK
  ui.apps/src/main/content/jcr_root/apps/venia/clientlibs/clientlib-cif/.content.xml
Labels: enhancement

#144 CIF-2154 - Improve UI tests for commerce content fragment component
  ui.tests/test-module/specs/venia/content-fragment-component-dialog.js
Labels: bug

#145 CIF-2097 - Consume the configured values in MagentoGraphqlClient and Config Exporters
  ui.frontend/src/main/components/App/App.js
Labels: enhancement, verified

#146 releng - Update CIF Core Components to version 1.12.0
  pom.xml
  ui.frontend/package-lock.json
  ui.frontend/package.json
Labels: releng

#149 2.0.0 ee
  .circleci/ci/it-tests.js
  pom.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/product/.content.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/productlist/.content.xml
  ui.frontend/package-lock.json
  ui.frontend/src/main/site/_variables.scss
  ui.frontend/src/main/styles/commerce/_product.scss
  ui.frontend/src/main/styles/commerce/_productlist.scss
Labels: enhancement

#142 CIF-1724: Add Magento Storefront Events Collector
  ui.apps/src/main/content/jcr_root/apps/venia/clientlibs/clientlib-cif/.content.xml
Labels: enhancement

#154 CIF-2137: Remove implementation of deprecated API
  core/src/main/java/com/venia/core/models/commerce/MyProductTeaserImpl.java
  core/src/test/java/com/venia/core/models/commerce/MyProductTeaserImplTest.java
Labels: enhancement

#151 CIF-2131 - remove "id" support for AEM Venia
  it.tests/src/main/java/com/venia/it/tests/CategoryPageIT.java
  it.tests/src/main/resources/datalayer/grouped-product.json
  it.tests/src/main/resources/datalayer/simple-product.json
  ui.config/src/main/content/jcr_root/apps/venia/osgiconfig/config.publish/com.adobe.cq.commerce.core.components.internal.services.UrlProviderImpl.cfg.json
  ui.config/src/main/content/jcr_root/apps/venia/osgiconfig/config/com.adobe.cq.commerce.core.components.internal.services.UrlProviderImpl.cfg.json
  ui.content/src/main/content/jcr_root/conf/venia/settings/cloudconfigs/commerce/.content-classic.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/cloudconfigs/commerce/.content-cloud.xml
Labels: enhancement
