Repository adobe/aem-cif-guides-venia, pull requests merged in 2021-12, with the labels that each got.

#231 releng - updated CIF components version and GraphQL Client version to latest
  pom.xml
  ui.frontend/package-lock.json
  ui.frontend/package.json
Labels: releng

#233 CIF-2585 - fix Venia ui.tests running via mvn
  ui.tests/Dockerfile
  ui.tests/docker-compose-wdio-chrome.yaml
  ui.tests/docker-compose-wdio-firefox.yaml
  ui.tests/pom.xml
  ui.tests/test-module/specs/venia/react.js
Labels: bug

#229 CIF-2539: Add wish list component to Venia
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/wishlist/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/en/my-account/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/en/my-account/wishlist/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/my-account/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/my-account/wishlist/.content.xml
  ui.frontend/i18n/en.json
  ui.frontend/package-lock.json
  ui.frontend/package.json
  ui.frontend/src/main/components/AccountMenu/__tests__/__snapshots__/accountMenuItems.spec.js.snap
  ui.frontend/src/main/components/AccountMenu/useAccountMenuItems.js
  ui.frontend/src/main/components/AddressBookPage/__tests__/addressBookPage.spec.js
  ui.frontend/src/main/components/AddressBookPage/addressBookPage.js
  ui.frontend/src/main/components/App/App.js
  ui.frontend/src/main/components/App/config.js
  ui.frontend/src/main/components/Header/accountTrigger.js
  ui.frontend/src/main/components/Header/cartTrigger.js
  ui.frontend/src/main/components/OrderHistoryPage/__tests__/orderHistoryPage.spec.js
  ui.frontend/src/main/components/OrderHistoryPage/orderHistoryPage.js
  ui.frontend/src/main/components/WishlistPage/__tests__/__snapshots__/wishlist.spec.js.snap
  ui.frontend/src/main/components/WishlistPage/__tests__/__snapshots__/wishlistPage.spec.js.snap
  ui.frontend/src/main/components/WishlistPage/__tests__/wishlist.spec.js
  ui.frontend/src/main/components/WishlistPage/__tests__/wishlistPage.spec.js
  ui.frontend/src/main/components/WishlistPage/index.js
  ui.frontend/src/main/components/WishlistPage/wishlist.gql.js
  ui.frontend/src/main/components/WishlistPage/wishlist.js
  ui.frontend/src/main/components/WishlistPage/wishlistPage.js
Labels: enhancement

#236 CIF-2407: Add Wish List functionality
  core/src/main/java/com/venia/core/models/commerce/MyProductTeaserImpl.java
  core/src/test/java/com/venia/core/models/commerce/MyProductTeaserImplTest.java
  pom.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/wishlist/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/catalog-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/landing-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/page-content/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/root-page/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/xf-web-variation/policies/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/en/my-account/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/en/my-account/wishlist/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/my-account/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/my-account/wishlist/.content.xml
  ui.frontend/i18n/en.json
  ui.frontend/package-lock.json
  ui.frontend/package.json
  ui.frontend/src/main/components/AccountMenu/__tests__/__snapshots__/accountMenuItems.spec.js.snap
  ui.frontend/src/main/components/AccountMenu/__tests__/accountMenuItems.spec.js
  ui.frontend/src/main/components/AccountMenu/accountMenu.js
  ui.frontend/src/main/components/AccountMenu/accountMenuItems.js
  ui.frontend/src/main/components/AccountMenu/useAccountMenuItems.js
  ui.frontend/src/main/components/AddressBookPage/__tests__/addressBookPage.spec.js
  ui.frontend/src/main/components/AddressBookPage/addressBookPage.js
  ui.frontend/src/main/components/App/App.js
  ui.frontend/src/main/components/App/config.js
  ui.frontend/src/main/components/Header/accountTrigger.js
  ui.frontend/src/main/components/Header/cartTrigger.js
  ui.frontend/src/main/components/OrderHistoryPage/__tests__/orderHistoryPage.spec.js
  ui.frontend/src/main/components/OrderHistoryPage/orderHistoryPage.js
  ui.frontend/src/main/components/WishlistPage/__tests__/__snapshots__/wishlist.spec.js.snap
  ui.frontend/src/main/components/WishlistPage/__tests__/__snapshots__/wishlistPage.spec.js.snap
  ui.frontend/src/main/components/WishlistPage/__tests__/wishlist.spec.js
  ui.frontend/src/main/components/WishlistPage/__tests__/wishlistPage.spec.js
  ui.frontend/src/main/components/WishlistPage/index.js
  ui.frontend/src/main/components/WishlistPage/wishlist.gql.js
  ui.frontend/src/main/components/WishlistPage/wishlist.js
  ui.frontend/src/main/components/WishlistPage/wishlistPage.js
  ui.frontend/src/main/styles/commerce/_product.scss
  ui.frontend/src/main/talons/AddressBookPage/useAddressBookPage.js
Labels: verified

#237 CIF-2563 - Remove broken product links from cart and order history
  ui.frontend/i18n/en.json
  ui.frontend/src/main/components/CartPage/ProductListing/__tests__/__snapshots__/product.spec.js.snap
  ui.frontend/src/main/components/CartPage/ProductListing/product.js
  ui.frontend/src/main/components/MiniCart/ProductList/__tests__/__snapshots__/item.spec.js.snap
  ui.frontend/src/main/components/MiniCart/ProductList/__tests__/__snapshots__/productList.spec.js.snap
  ui.frontend/src/main/components/MiniCart/ProductList/__tests__/item.spec.js
  ui.frontend/src/main/components/MiniCart/ProductList/__tests__/productList.spec.js
  ui.frontend/src/main/components/MiniCart/ProductList/index.js
  ui.frontend/src/main/components/MiniCart/ProductList/item.js
  ui.frontend/src/main/components/MiniCart/ProductList/productList.js
  ui.frontend/src/main/components/MiniCart/miniCart.js
  ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/__tests__/__snapshots__/item.spec.js.snap
  ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/__tests__/__snapshots__/items.spec.js.snap
  ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/__tests__/__snapshots__/orderDetails.spec.js.snap
  ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/__tests__/item.spec.js
  ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/__tests__/items.spec.js
  ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/__tests__/orderDetails.spec.js
  ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/index.js
  ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/item.js
  ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/items.js
  ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/orderDetails.js
  ui.frontend/src/main/components/OrderHistoryPage/__tests__/__snapshots__/orderRow.spec.js.snap
  ui.frontend/src/main/components/OrderHistoryPage/__tests__/orderHistoryPage.spec.js
  ui.frontend/src/main/components/OrderHistoryPage/__tests__/orderRow.spec.js
  ui.frontend/src/main/components/OrderHistoryPage/orderHistoryPage.js
  ui.frontend/src/main/components/OrderHistoryPage/orderRow.js
Labels: bug
