Repository adobe/aem-cif-guides-venia, pull requests merged in 2021-04, with the labels that each got.

#125 CIF-2015 - Migrate to Azul Zulu JDK
  .circleci/config.yml
Labels: releng

#128 Readme.md
  ui.frontend/README.md
Labels: documentation

#127 CIF-2039 - Missing root category field in catalog page properties
  ui.tests/test-module/specs/venia/catalog-page-dialogs.js
Labels: bug

#126 CIF-1907 - Build navigation component based on WCM Core Component
  it.tests/src/main/java/com/venia/it/tests/CommerceTestBase.java
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/navigation/.content.xml
  ui.frontend/src/main/site/styles/header.scss
  ui.frontend/src/main/styles/commerce/_navigation.scss
  ui.tests/test-module/specs/venia/react.js
Labels: enhancement
