Repository adobe/aem-cif-guides-venia, pull requests merged in 2021-03, with the labels that each got.

#109 CIF-1958 - Add missing cq:lastModified property to sample XF in Venia
  ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/footer/master/.content.xml
  ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/header/master/.content.xml
  ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/products/promotions/master/.content.xml
Labels: To Verify, bug

#114 CIF-1920 - Move XFPage dialog extensions to CIF core components
  .gitignore
  ui.apps/pom.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/xfpage/.content.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/xfpage/_cq_dialog/.content-classic.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/xfpage/_cq_dialog/.content-cloud.xml
  ui.tests/test-module/lib/config.js
  ui.tests/test-module/specs/venia/xf-page-dialogs.js
Labels: refactoring

#115 CIF-1964 - Show staged flag in product component
  .circleci/ci/it-tests.js
  pom.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/product/.content.xml
  ui.frontend/src/main/styles/commerce/_product.scss
Labels: To Verify, enhancement

#119 Add CTA text to JSON export
  core/src/main/java/com/venia/core/models/commerce/MyProductTeaserImpl.java
  core/src/test/java/com/venia/core/models/commerce/MyProductTeaserImplTest.java
Labels: bug

#118 CIF-1965 - Show staged flag in productlist component
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/productlist/.content.xml
  ui.frontend/src/main/site/_variables.scss
  ui.frontend/src/main/styles/commerce/_product.scss
  ui.frontend/src/main/styles/commerce/_productlist.scss
Labels: enhancement

#112 CIF-1921 - Minimal default styling for featured category list
  ui.apps/src/main/content/jcr_root/apps/venia/clientlibs/clientlib-cif/.content.xml
Labels: enhancement

#117 CIF-1922 - Minimal default styling for product teaser
  ui.frontend/src/main/styles/commerce/_productteaser.scss
Labels: bug

#124 CIF-1718 - Adopt Magento GraphQL schema changes - Category UID
  .circleci/ci/it-tests.js
  pom.xml
Labels: releng
