Repository adobe/aem-cif-guides-venia, pull requests merged in 2021-09, with the labels that each got.

#189 CIF-2385: remove skus from placeholder data in categrory page it
  it.tests/src/main/resources/datalayer/placeholder-category-items.json
Labels: bug

#187 trivial - Remove empty asset.jpg node
  ui.content/src/main/content/jcr_root/content/dam/venia/.content.xml
Labels: bug

#181 CIF-2246: Update Venia ui.frontend dependencies
  ui.frontend/package-lock.json
  ui.frontend/package.json
  ui.frontend/pom.xml
  ui.frontend/webpack.common.js
  ui.frontend/webpack.dev.js
  ui.frontend/webpack.prod.js
Labels: enhancement

#190 CIF-2384: Migrate to react-intl
  ui.frontend/package-lock.json
  ui.frontend/package.json
  ui.frontend/src/main/components/App/App.js
  ui.frontend/src/main/components/App/i18n.js
  ui.frontend/src/main/i18n/en.js
  ui.frontend/webpack.common.js
Labels: breaking

#192 CIF-2382 - Content Fragment Component Dialog test fails against Skyline instance
  ui.tests/test-module/specs/venia/content-fragment-component-dialog.js
  ui.tests/test-module/specs/venia/searchbar.js
Labels: bug

#193 releng - update CIF components to 2.2.0
  pom.xml
  ui.frontend/package-lock.json
  ui.frontend/package.json
Labels: releng

#194 Release 2021.09.23
  it.tests/src/main/resources/datalayer/placeholder-category-items.json
  pom.xml
  ui.content/src/main/content/jcr_root/content/dam/venia/.content.xml
  ui.frontend/package-lock.json
  ui.frontend/package.json
  ui.frontend/pom.xml
  ui.frontend/src/main/components/App/App.js
  ui.frontend/src/main/components/App/i18n.js
  ui.frontend/src/main/i18n/en.js
  ui.frontend/webpack.common.js
  ui.frontend/webpack.dev.js
  ui.frontend/webpack.prod.js
  ui.tests/test-module/specs/venia/content-fragment-component-dialog.js
  ui.tests/test-module/specs/venia/searchbar.js
Labels: releng

#197 CIF-2432 - update /etc/map configs to work with url suffix
  ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/category-page-reverse/.content.xml
  ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/category-page/.content.xml
  ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/product-page-reverse/.content.xml
  ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/product-page/.content.xml
Labels: bug
