Repository adobe/aem-cif-guides-venia, pull requests merged in 2021-01, with the labels that each got.

#93 CIF-1772 - Fix footer styling in Venia demo
  ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/footer/master/.content.xml
  ui.frontend/src/main/site/styles/footer.scss
Labels: bug

#92 Update ui.tests README to include instructions regarding Chromedriver version
  ui.tests/README.md
  ui.tests/test-module/wdio.conf.local.js
Labels: bug, documentation

#94 CIF-1512 - Dynamic XF on PDP
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/experiencefragment/.content.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/xfpage/_cq_dialog/.content-cloud.xml
Labels: enhancement, verified

#96 CIF-1674 - Add UI tests for component dialogs
  .circleci/ci/it-tests.js
  pom.xml
  ui.tests/test-module/lib/commons.js
  ui.tests/test-module/lib/wdio.commands.js
  ui.tests/test-module/specs/venia/component-dialogs.js
Labels: testing

#97 CIF-1818: Category reference tab + picker for Experience Fragments
  ui.apps/src/main/content/jcr_root/apps/venia/components/xfpage/_cq_dialog/.content-cloud.xml
Labels: enhancement
