Repository adobe/aem-cif-guides-venia, pull requests merged in 2021-07, with the labels that each got.

#150 CIF-2062 - adjust URLProvider config and Sling map
  it.tests/src/main/java/com/venia/it/tests/CategoryPageIT.java
  it.tests/src/main/java/com/venia/it/tests/ProductPageIT.java
  ui.config/src/main/content/jcr_root/apps/venia/osgiconfig/config.publish/com.adobe.cq.commerce.core.components.internal.services.UrlProviderImpl.cfg.json
  ui.config/src/main/content/jcr_root/apps/venia/osgiconfig/config/com.adobe.cq.commerce.core.components.internal.services.UrlProviderImpl.cfg.json
  ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/category-page-reverse/.content.xml
  ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/category-page/.content.xml
  ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/product-page-reverse/.content.xml
  ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/product-page/.content.xml
Labels: enhancement

#152 CIF-2143: Create Product Recommendations AEM component
  all/pom.xml
  core/pom.xml
  pom.xml
  ui.apps/pom.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/productrecommendations/.content.xml
Labels: enhancement

#155 CIF-2038 - Migrate to CircleCI contexts
  .circleci/config.yml
  .circleci/settings.xml
Labels: releng

#156 CIF-2153 - use Button component V2
  ui.apps/src/main/content/jcr_root/apps/venia/components/button/.content.xml
Labels: enhancement

#159 CIF-2193 - use CIF page V2 component
  ui.apps/src/main/content/jcr_root/apps/venia/components/page/.content.xml
Labels: breaking, enhancement

#162 CIF-2155 - Update to use new V2 commerce teaser
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/teaser/.content.xml
  ui.tests/test-module/specs/venia/component-dialogs.js
Labels: enhancement

#167 CIF-2222: Add config for storefront context render
  ui.content/src/main/content/jcr_root/conf/venia/_sling_configs/.content.xml
  ui.frontend/.eslintignore
Labels: enhancement

#166 CIF-2227 - add missing image alt attribute for product teaser component
  core/src/main/java/com/venia/core/models/commerce/MyProductTeaserImpl.java
  core/src/test/java/com/venia/core/models/commerce/MyProductTeaserImplTest.java
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/productteaser/productteaser.html
Labels: bug

#153 CIF-2144 - Create a React project with a Recommendation component
  .circleci/config.yml
  pom.xml
  ui.frontend/README.md
  ui.frontend/package-lock.json
  ui.frontend/package.json
  ui.frontend/pom.xml
  ui.frontend/src/main/components/App/App.js
  ui.frontend/src/main/components/App/i18n.js
  ui.frontend/src/main/site/main.scss
  ui.frontend/webpack.common.js
  ui.frontend/webpack.dev.js
Labels: enhancement

#172 CIF-2144 - Disable mangling because of bug in graphql library
  ui.frontend/pom.xml
  ui.frontend/webpack.prod.js
Labels: bug

#161 CIF-2111 - Add E2E test for product recommendation component
  ui.tests/test-module/specs/venia/component-dialogs.js
Labels: testing
