Repository adobe/aem-cif-guides-venia, pull requests merged in 2021-02, with the labels that each got.

#99 CIF-1849 - Create minimal default styling for product carousel
  ui.apps/src/main/content/jcr_root/apps/venia/components/page/customheaderlibs.html
Labels: enhancement

#101 CIF-1931, CIF-1932 - rename component and XF properties field
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/experiencefragment/.content.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/xfpage/_cq_dialog/.content-cloud.xml
  ui.tests/test-module/specs/venia/component-dialogs.js
Labels: To Verify, bug

#100 CIF-1906 - Minimal default styling for category carousel
  ui.apps/src/main/content/jcr_root/apps/venia/clientlibs/clientlib-cif/.content.xml
Labels: enhancement, verified

#103 CIF-1943 - add sample PDP XF and placeholder for Venia
  core/pom.xml
  ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/products/.content.xml
  ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/products/promotions/.content.xml
  ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/products/promotions/master/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/en/products/product-page/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/products/product-page/.content.xml
Labels: To Verify, enhancement

#105 CIF-1902 - Some files in Venia AMS Dispatcher config should be symbol…
  dispatcher-ams/src/conf.d/enabled_vhosts/aem_author.vhost
  dispatcher-ams/src/conf.d/enabled_vhosts/aem_flush.vhost
  dispatcher-ams/src/conf.d/enabled_vhosts/aem_health.vhost
  dispatcher-ams/src/conf.d/enabled_vhosts/venia_publish.vhost
  dispatcher-ams/src/conf.dispatcher.d/enabled_farms/000_ams_author_farm.any
  dispatcher-ams/src/conf.dispatcher.d/enabled_farms/999_ams_publish_farm.any
Labels: bug

#104 releng - Update AEM and AEMaaCS docker image versions
  .circleci/config.yml
Labels: releng
