Repository adobe/aem-cif-guides-venia, pull requests merged in 2022-05, with the labels that each got.

#277 CIF-2736 - Support custom sort keys in product listing components
  it.tests/src/main/resources/datalayer/sample-category-items.json
  pom.xml
  ui.content/src/main/content/jcr_root/content/venia/language-masters/en/search/.content.xml
  ui.content/src/main/content/jcr_root/content/venia/us/en/search/.content.xml
  ui.tests/test-module/specs/venia/component-dialogs.js
  ui.tests/test-module/specs/venia/productlist-dialog.js
Labels: enhancement, verified

#279 CIF-2727 - Category Carousel: add option to open CTA in a new Tab
  ui.tests/test-module/specs/venia/component-dialogs.js
  ui.tests/test-module/specs/venia/productcarousel-dialog.js
Labels: enhancement

#281 CIF-2289: update Venia to use v3 page
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/catalogpage/.content.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/page/.content.xml
Labels: enhancement

#283 CIF-2884 - Commerce teaser dialog clientlib regressions
  ui.tests/test-module/lib/wdio.commands.js
  ui.tests/test-module/specs/venia/commerceteasser-dialog.js
  ui.tests/test-module/specs/venia/component-dialogs.js
Labels: bug, verified

#280 CIF-2732 - Teaser: add option to open CTA in a new Tab
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/teaser/.content.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/teaser/.content.xml
  ui.tests/test-module/lib/wdio.commands.js
  ui.tests/test-module/specs/venia/commerceteasser-dialog.js
  ui.tests/test-module/specs/venia/component-dialogs.js
Labels: enhancement, verified

#284 CIF-2836: Update swatch color style
  ui.frontend/src/main/styles/commerce/_product.scss
Labels: enhancement
