Repository adobe/aem-cif-guides-venia, pull requests merged in 2022-02, with the labels that each got.

#249 CIF-2114: properly impersonate when updating CM repo
  .circleci/ci/ci.js
  .circleci/ci/update-cm.js
  .circleci/config.yml
Labels: releng

#251 CIF-2678 - Styling is broken on catalog page in Venia and archetype projects
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/catalogpage/customheaderlibs.html
Labels: bug, verified

#252 CIF-2638 - Move navigation styling to Venia
  ui.apps/src/main/content/jcr_root/apps/venia/clientlibs/clientlib-cif/.content.xml
  ui.frontend/src/main/styles/commerce/_navigation.scss
Labels: enhancement

#257 CIF-2695 - fix readme links & wording
  README.md
Labels: documentation

#260 releng: update cif core components to 2.6.0
  pom.xml
  ui.frontend/package-lock.json
  ui.frontend/package.json
Labels: releng

#261 Release 2022.02.24
  .circleci/ci/ci.js
  .circleci/ci/update-cm.js
  .circleci/config.yml
  README.md
  pom.xml
  ui.apps/src/main/content/jcr_root/apps/venia/clientlibs/clientlib-cif/.content.xml
  ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/catalogpage/customheaderlibs.html
  ui.frontend/package-lock.json
  ui.frontend/package.json
  ui.frontend/src/main/styles/commerce/_navigation.scss
  ui.tests/test-module/specs/venia/component-dialogs.js
  ui.tests/test-module/specs/venia/productcarousel-dialog.js
  ui.tests/test-module/specs/venia/productlist-dialog.js
Labels: releng

#246 releng - Update Docker images to AEMaaCS 6198 and AEM 6.5.11
  .circleci/config.yml
Labels: releng
