Repository adobe/aem-cif-guides-venia, pull requests merged in 2022-01, with the labels that each got.

#239 fix: remove `rm` command from i18n:extract-compile
  .gitignore
  ui.frontend/package.json
Labels: bug, verified

#240 CIF-2114: Update Cloud Manager repositories for each release
  .circleci/config.yml
Labels: releng

#242 CIF-2603 - Add visual indication for add to wishlist
  ui.frontend/i18n/en.json
  ui.frontend/package-lock.json
  ui.frontend/package.json
  ui.frontend/src/main/components/App/App.js
  ui.frontend/src/main/components/Header/accountTrigger.js
  ui.frontend/src/main/components/Peregrine/__tests__/useToastEvents.spec.js
  ui.frontend/src/main/components/Peregrine/useToastEvents.js
Labels: enhancement

#241 CIF-2508 - Move secrets from Zerobin to Vault
  ui.tests/README.md
Labels: verified, releng

#243 CIF-2503: update url provider configuration to use new features
  ui.config/src/main/content/jcr_root/apps/venia/osgiconfig/config/com.adobe.cq.commerce.core.components.internal.services.UrlProviderImpl.cfg.json
Labels: verified

#245 CIF-2646: move /content/venia => / mapping to etc/map
  ui.config/src/main/content/jcr_root/apps/venia/osgiconfig/config.publish/org.apache.sling.jcr.resource.internal.JcrResourceResolverFactoryImpl.cfg.json
  ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/.content.xml
  ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/category-page/.content.xml
  ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/product-page/.content.xml
Labels: bug, verified

#244 CIF-1675: make Venia IT and UI tests pass on CM
  .circleci/ci/it-tests.js
  it.tests/pom.xml
  it.tests/src/main/java/com/venia/it/tests/CategoryPageIT.java
  it.tests/src/main/java/com/venia/it/tests/CommerceTestBase.java
  it.tests/src/main/java/com/venia/it/tests/ProductPageIT.java
  it.tests/src/main/java/junit/category/IgnoreOn65.java
  it.tests/src/main/java/junit/category/IgnoreOnCloud.java
  ui.tests/Dockerfile
  ui.tests/assembly-ui-test-docker-context.xml
  ui.tests/docker-compose-wdio-chrome.yaml
  ui.tests/docker-compose-wdio-firefox.yaml
  ui.tests/pom.xml
  ui.tests/testing.properties
Labels: bug, verified, releng

#247 releng - Update CIF Core Components version to 2.5.0
  pom.xml
  ui.frontend/package-lock.json
  ui.frontend/package.json
Labels: releng
